// site2.js — second half of the landing-page copy (compression, privacy, how it
// works, roadmap, CTA, footer). Split from site.js only to keep each file
// readable; tools/build-website.js merges them. Same keying rules — see the
// header of site.js.
"use strict";

const SITE2 = {
  // ── AI compression ────────────────────────────────────────────────────
  "AI compression": { es: "Compresión con IA", pt_BR: "Compressão com IA", de: "KI-Komprimierung", fr: "Compression IA", ja: "AI 圧縮", zh_CN: "AI 压缩", ru: "Сжатие с помощью ИИ", ko: "AI 압축", it: "Compressione IA", tr: "Yapay zeka sıkıştırması" },
  "Trim tokens by up to": { es: "Recorta tokens hasta un", pt_BR: "Corte tokens em até", de: "Bis zu", fr: "Réduisez les tokens jusqu'à", ja: "トークンを最大", zh_CN: "token 最多减少", ru: "Сократите токены до", ko: "토큰을 최대", it: "Riduci i token fino al", tr: "Token'ları" },
  "Condense a long chat into a structured hand-off brief, organized by completed work, current state, next steps, and the constraints that matter. Your decisions, code, and images are kept; the noise is summarized.": {
    es: "Condensa un chat largo en un resumen de traspaso estructurado, organizado por trabajo completado, estado actual, próximos pasos y las restricciones que importan. Tus decisiones, código e imágenes se conservan; el ruido se resume.",
    pt_BR: "Condense uma conversa longa em um resumo de transição estruturado, organizado por trabalho concluído, estado atual, próximos passos e as restrições que importam. Suas decisões, código e imagens são preservados; o ruído é resumido.",
    de: "Verdichte einen langen Chat zu einem strukturierten Übergabe-Briefing, gegliedert nach erledigter Arbeit, aktuellem Stand, nächsten Schritten und den Rahmenbedingungen, auf die es ankommt. Deine Entscheidungen, dein Code und deine Bilder bleiben; der Rest wird zusammengefasst.",
    fr: "Condensez un long chat en une synthèse de passation structurée, organisée par travail effectué, état actuel, prochaines étapes et contraintes qui comptent. Vos décisions, votre code et vos images sont conservés ; le bruit est résumé.",
    ja: "長い会話を、完了した作業・現在の状態・次のステップ・重要な制約で整理された引き継ぎブリーフに凝縮します。決定事項、コード、画像は残し、それ以外は要約します。",
    zh_CN: "把长对话浓缩成结构化的交接摘要，按已完成的工作、当前状态、下一步和关键限制条件组织。你的决定、代码和图片会保留，其余内容被概括。",
    ru: "Сожмите длинный диалог в структурированную сводку, разложенную по выполненной работе, текущему состоянию, следующим шагам и значимым ограничениям. Ваши решения, код и изображения сохраняются, остальное резюмируется.",
    ko: "긴 대화를 완료된 작업, 현재 상태, 다음 단계, 중요한 제약으로 정리된 인계 요약으로 압축합니다. 결정과 코드, 이미지는 남기고 나머지는 요약합니다.",
    it: "Condensa una chat lunga in una sintesi di passaggio strutturata, organizzata per lavoro completato, stato attuale, prossimi passi e i vincoli che contano. Decisioni, codice e immagini restano; il rumore viene riassunto.",
    tr: "Uzun bir sohbeti; tamamlanan iş, mevcut durum, sonraki adımlar ve önemli kısıtlara göre düzenlenmiş yapılandırılmış bir devir özetine indirgeyin. Kararlarınız, kodunuz ve görselleriniz korunur, gerisi özetlenir.",
  },
  "Bring your own provider and key": { es: "Usa tu propio proveedor y clave", pt_BR: "Use seu próprio provedor e chave", de: "Eigener Anbieter, eigener Schlüssel", fr: "Votre propre fournisseur et votre clé", ja: "プロバイダーとキーはご自身のものを", zh_CN: "自带服务商和密钥", ru: "Свой провайдер и свой ключ", ko: "제공업체와 키는 직접 준비", it: "Usa il tuo provider e la tua chiave", tr: "Kendi sağlayıcınızı ve anahtarınızı kullanın" },
  "Key stored locally, sent only to that provider": { es: "La clave se guarda en local y solo se envía a ese proveedor", pt_BR: "A chave fica local e é enviada só para aquele provedor", de: "Schlüssel lokal gespeichert, nur an diesen Anbieter gesendet", fr: "Clé stockée en local, envoyée uniquement à ce fournisseur", ja: "キーはローカル保存、そのプロバイダーにのみ送信", zh_CN: "密钥保存在本地，只发送给该服务商", ru: "Ключ хранится локально и уходит только этому провайдеру", ko: "키는 로컬에 저장되고 해당 제공업체로만 전송", it: "Chiave salvata in locale, inviata solo a quel provider", tr: "Anahtar yerelde saklanır, yalnızca o sağlayıcıya gönderilir" },
  "Lifetime token savings tracked in the panel": { es: "El ahorro total de tokens se registra en el panel", pt_BR: "A economia total de tokens fica registrada no painel", de: "Gesamte Token-Ersparnis wird im Panel mitgeführt", fr: "Les économies de tokens cumulées sont suivies dans le panneau", ja: "累計のトークン削減量はパネルで確認できます", zh_CN: "累计节省的 token 会在面板中记录", ru: "Общая экономия токенов видна в панели", ko: "누적 토큰 절감량은 패널에서 확인", it: "Il risparmio complessivo di token è tracciato nel pannello", tr: "Toplam token tasarrufu panelde izlenir" },
  "See an example brief": { es: "Ver un resumen de ejemplo", pt_BR: "Ver um resumo de exemplo", de: "Beispiel-Briefing ansehen", fr: "Voir un exemple de synthèse", ja: "ブリーフの例を見る", zh_CN: "查看摘要示例", ru: "Посмотреть пример сводки", ko: "요약 예시 보기", it: "Vedi una sintesi di esempio", tr: "Örnek bir özet görün" },

  // ── Privacy ───────────────────────────────────────────────────────────
  "% local.": { es: "% local.", pt_BR: "% local.", de: "% lokal.", fr: "% local.", ja: "% ローカル。", zh_CN: "% 本地。", ru: "% локально.", ko: "% 로컬.", it: "% locale.", tr: "% yerel." },
  "No account, no servers.": { es: "Sin cuenta, sin servidores.", pt_BR: "Sem conta, sem servidores.", de: "Kein Konto, keine Server.", fr: "Sans compte, sans serveurs.", ja: "アカウントもサーバーも不要。", zh_CN: "无需账号，没有服务器。", ru: "Без аккаунта, без серверов.", ko: "계정도 서버도 없이.", it: "Nessun account, nessun server.", tr: "Hesap yok, sunucu yok." },
  "Your chats and keys never leave your device. No tracking, no analytics, no cloud. Make it yours with dark mode, auto-send, and an editable hand-off message.": {
    es: "Tus chats y claves nunca salen de tu dispositivo. Sin rastreo, sin analíticas, sin nube. Hazlo tuyo con modo oscuro, envío automático y un mensaje de traspaso editable.",
    pt_BR: "Suas conversas e chaves nunca saem do seu dispositivo. Sem rastreamento, sem analytics, sem nuvem. Deixe do seu jeito com modo escuro, envio automático e mensagem de transição editável.",
    de: "Deine Chats und Schlüssel verlassen dein Gerät nie. Kein Tracking, keine Analytics, keine Cloud. Mach es zu deinem: Dunkelmodus, Auto-Senden und eine editierbare Übergabenachricht.",
    fr: "Vos chats et vos clés ne quittent jamais votre appareil. Aucun pistage, aucune analytique, aucun cloud. Personnalisez : mode sombre, envoi auto et message de passation modifiable.",
    ja: "チャットもキーも端末から出ません。トラッキングなし、解析なし、クラウドなし。ダークモード、自動送信、編集できる引き継ぎメッセージで自分好みに。",
    zh_CN: "对话和密钥从不离开你的设备。不追踪、不分析、不上云。深色模式、自动发送和可编辑的交接消息，随你调整。",
    ru: "Чаты и ключи никогда не покидают устройство. Без трекинга, без аналитики, без облака. Настройте под себя: тёмная тема, автоотправка и редактируемое сообщение-передача.",
    ko: "대화와 키는 기기를 벗어나지 않습니다. 추적 없음, 분석 없음, 클라우드 없음. 다크 모드와 자동 전송, 편집 가능한 인계 메시지로 원하는 대로.",
    it: "Le tue chat e le tue chiavi non lasciano mai il dispositivo. Nessun tracciamento, nessuna analitica, nessun cloud. Rendila tua con modalità scura, invio automatico e messaggio di passaggio modificabile.",
    tr: "Sohbetleriniz ve anahtarlarınız cihazınızdan çıkmaz. Takip yok, analitik yok, bulut yok. Koyu mod, otomatik gönderim ve düzenlenebilir devir mesajıyla size özel.",
  },
  "No sign-up": { es: "Sin registro", pt_BR: "Sem cadastro", de: "Keine Anmeldung", fr: "Sans inscription", ja: "登録不要", zh_CN: "无需注册", ru: "Без регистрации", ko: "가입 불필요", it: "Nessuna registrazione", tr: "Kayıt yok" },
  "No servers": { es: "Sin servidores", pt_BR: "Sem servidores", de: "Keine Server", fr: "Sans serveurs", ja: "サーバーなし", zh_CN: "没有服务器", ru: "Без серверов", ko: "서버 없음", it: "Nessun server", tr: "Sunucu yok" },
  "No tracking": { es: "Sin rastreo", pt_BR: "Sem rastreamento", de: "Kein Tracking", fr: "Sans pistage", ja: "トラッキングなし", zh_CN: "不做追踪", ru: "Без трекинга", ko: "추적 없음", it: "Nessun tracciamento", tr: "Takip yok" },
  "Open source": { es: "Código abierto", pt_BR: "Código aberto", de: "Open Source", fr: "Open source", ja: "オープンソース", zh_CN: "开源", ru: "Открытый код", ko: "오픈 소스", it: "Open source", tr: "Açık kaynak" },
  "Read the full privacy policy": { es: "Leer la política de privacidad completa", pt_BR: "Ler a política de privacidade completa", de: "Vollständige Datenschutzerklärung lesen", fr: "Lire la politique de confidentialité complète", ja: "プライバシーポリシー全文を読む", zh_CN: "阅读完整隐私政策", ru: "Читать полную политику конфиденциальности", ko: "전체 개인정보 처리방침 읽기", it: "Leggi l'informativa sulla privacy completa", tr: "Gizlilik politikasının tamamını okuyun" },

  // ── How it works ──────────────────────────────────────────────────────
  "Three steps. Full context, every time.": { es: "Tres pasos. Todo el contexto, siempre.", pt_BR: "Três passos. Contexto completo, sempre.", de: "Drei Schritte. Jedes Mal voller Kontext.", fr: "Trois étapes. Tout le contexte, à chaque fois.", ja: "3ステップ。毎回、完全な文脈で。", zh_CN: "三步搞定，每次都保留完整上下文。", ru: "Три шага. Полный контекст каждый раз.", ko: "세 단계. 매번 완전한 맥락으로.", it: "Tre passaggi. Contesto completo, ogni volta.", tr: "Üç adım. Her seferinde tam bağlam." },
  Capture: { es: "Captura", pt_BR: "Capture", de: "Sichern", fr: "Capturer", ja: "保存", zh_CN: "捕获", ru: "Сохранение", ko: "저장", it: "Cattura", tr: "Yakala" },
  "Open the panel on any supported AI and save the live conversation in one click.": { es: "Abre el panel en cualquier IA compatible y guarda la conversación en curso con un clic.", pt_BR: "Abra o painel em qualquer IA compatível e salve a conversa ao vivo com um clique.", de: "Öffne das Panel bei jeder unterstützten KI und sichere die laufende Unterhaltung mit einem Klick.", fr: "Ouvrez le panneau sur n'importe quelle IA compatible et enregistrez la conversation en cours en un clic.", ja: "対応するAIでパネルを開き、進行中の会話をワンクリックで保存。", zh_CN: "在任意受支持的 AI 上打开面板，一键保存正在进行的对话。", ru: "Откройте панель в любом поддерживаемом ИИ и сохраните текущий диалог одним кликом.", ko: "지원되는 AI에서 패널을 열고 진행 중인 대화를 클릭 한 번으로 저장하세요.", it: "Apri il pannello su qualsiasi IA supportata e salva la conversazione in corso con un clic.", tr: "Desteklenen herhangi bir yapay zekâda paneli açın ve süren sohbeti tek tıkla kaydedin." },
  "Messages, images, files, and code, stored exactly as shown, on your device.": { es: "Mensajes, imágenes, archivos y código, guardados tal como se ven, en tu dispositivo.", pt_BR: "Mensagens, imagens, arquivos e código, salvos exatamente como aparecem, no seu dispositivo.", de: "Nachrichten, Bilder, Dateien und Code — genau so gespeichert, wie sie angezeigt werden, auf deinem Gerät.", fr: "Messages, images, fichiers et code, stockés exactement tels qu'affichés, sur votre appareil.", ja: "メッセージ・画像・ファイル・コードを、表示されたままの形で端末に保存。", zh_CN: "消息、图片、文件和代码，按显示的样子原样保存在你的设备上。", ru: "Сообщения, изображения, файлы и код — сохранены ровно так, как показаны, на вашем устройстве.", ko: "메시지와 이미지, 파일, 코드를 보이는 그대로 기기에 저장합니다.", it: "Messaggi, immagini, file e codice, salvati esattamente come appaiono, sul tuo dispositivo.", tr: "Mesajlar, görseller, dosyalar ve kod, göründüğü gibi cihazınızda saklanır." },
  Resume: { es: "Continúa", pt_BR: "Continue", de: "Fortsetzen", fr: "Reprendre", ja: "再開", zh_CN: "继续", ru: "Продолжение", ko: "이어하기", it: "Riprendi", tr: "Sürdür" },
  "Pick a destination. Continuum opens a fresh chat and attaches the history.": { es: "Elige un destino. Continuum abre un chat nuevo y adjunta el historial.", pt_BR: "Escolha um destino. O Continuum abre um novo chat e anexa o histórico.", de: "Wähle ein Ziel. Continuum öffnet einen neuen Chat und hängt den Verlauf an.", fr: "Choisissez une destination. Continuum ouvre un nouveau chat et joint l'historique.", ja: "行き先を選ぶと、Continuum が新しいチャットを開いて履歴を添付します。", zh_CN: "选择去处，Continuum 会打开新对话并附上历史记录。", ru: "Выберите назначение. Continuum откроет новый чат и приложит историю.", ko: "목적지를 고르면 Continuum이 새 대화를 열고 기록을 첨부합니다.", it: "Scegli una destinazione. Continuum apre una nuova chat e allega la cronologia.", tr: "Bir hedef seçin. Continuum yeni bir sohbet açar ve geçmişi ekler." },
  "It writes the hand-off and uploads the PDF, or pastes the markdown, for you.": { es: "Escribe el traspaso y sube el PDF, o pega el markdown, por ti.", pt_BR: "Ele escreve a transição e envia o PDF, ou cola o markdown, por você.", de: "Es schreibt die Übergabe und lädt das PDF hoch oder fügt das Markdown für dich ein.", fr: "Il rédige la passation et téléverse le PDF, ou colle le markdown, à votre place.", ja: "引き継ぎ文を書き、PDF をアップロード、または Markdown を貼り付けます。", zh_CN: "它会写好交接消息并上传 PDF，或替你粘贴 markdown。", ru: "Он пишет передачу и загружает PDF или вставляет markdown за вас.", ko: "인계 메시지를 쓰고 PDF를 올리거나 markdown을 대신 붙여 넣습니다.", it: "Scrive il passaggio e carica il PDF, o incolla il markdown, al posto tuo.", tr: "Devir mesajını yazar ve PDF'i yükler ya da markdown'ı sizin yerinize yapıştırır." },
  Continue: { es: "Sigue", pt_BR: "Siga", de: "Weitermachen", fr: "Continuer", ja: "続ける", zh_CN: "接着聊", ru: "Дальше", ko: "계속", it: "Continua", tr: "Devam et" },
  "The model reads the context and picks up exactly where you left off.": { es: "El modelo lee el contexto y retoma justo donde lo dejaste.", pt_BR: "O modelo lê o contexto e continua exatamente de onde você parou.", de: "Das Modell liest den Kontext und macht genau da weiter, wo du aufgehört hast.", fr: "Le modèle lit le contexte et reprend exactement là où vous vous étiez arrêté.", ja: "モデルが文脈を読み取り、中断したところから正確に続けます。", zh_CN: "模型读取上下文，从你停下的地方精确接着往下走。", ru: "Модель читает контекст и продолжает ровно с того места, где вы остановились.", ko: "모델이 맥락을 읽고 멈춘 지점에서 정확히 이어갑니다.", it: "Il modello legge il contesto e riprende esattamente da dove eri rimasto.", tr: "Model bağlamı okur ve tam bıraktığınız yerden devam eder." },
  "No re-explaining. Same thread, any model, full memory of the work.": { es: "Sin volver a explicar. El mismo hilo, cualquier modelo, memoria completa del trabajo.", pt_BR: "Sem reexplicar. O mesmo fio, qualquer modelo, memória completa do trabalho.", de: "Kein Neu-Erklären. Derselbe Faden, jedes Modell, volle Erinnerung an die Arbeit.", fr: "Plus besoin de tout réexpliquer. Même fil, n'importe quel modèle, mémoire complète du travail.", ja: "説明のやり直しは不要。同じ流れのまま、どのモデルでも作業の記憶をすべて保ったまま。", zh_CN: "不用重新解释。同一条线索，任意模型，完整记得之前的工作。", ru: "Ничего не нужно объяснять заново. Та же нить, любая модель, полная память о работе.", ko: "다시 설명할 필요 없습니다. 같은 흐름, 어떤 모델이든, 작업 내용을 온전히 기억한 채로.", it: "Niente da rispiegare. Stesso filo, qualsiasi modello, memoria completa del lavoro.", tr: "Yeniden anlatmak yok. Aynı akış, herhangi bir model, işin tam hafızası." },

  // ── Roadmap ───────────────────────────────────────────────────────────
  "Coming soon": { es: "Muy pronto", pt_BR: "Em breve", de: "Demnächst", fr: "Bientôt", ja: "近日公開", zh_CN: "即将推出", ru: "Скоро", ko: "곧 출시", it: "Prossimamente", tr: "Yakında" },
  "More models and agents. Notes that sync.": { es: "Más modelos y agentes. Notas que se sincronizan.", pt_BR: "Mais modelos e agentes. Notas que sincronizam.", de: "Mehr Modelle und Agenten. Notizen, die sich synchronisieren.", fr: "Plus de modèles et d'agents. Des notes qui se synchronisent.", ja: "対応モデルとエージェントを拡大。ノートは同期。", zh_CN: "更多模型与智能体。笔记自动同步。", ru: "Больше моделей и агентов. Заметки с синхронизацией.", ko: "더 많은 모델과 에이전트. 동기화되는 노트.", it: "Più modelli e agenti. Note che si sincronizzano.", tr: "Daha çok model ve ajan. Senkronize olan notlar." },
  "Then, an app of its own.": { es: "Y después, una app propia.", pt_BR: "E depois, um app próprio.", de: "Und dann eine eigene App.", fr: "Puis, une app à part entière.", ja: "そして、専用アプリへ。", zh_CN: "然后，还有独立应用。", ru: "А затем — отдельное приложение.", ko: "그리고 전용 앱까지.", it: "E poi, un'app tutta sua.", tr: "Sonra da kendine ait bir uygulama." },
  "Continuum is just getting started. Here is what is next.": { es: "Continuum acaba de empezar. Esto es lo que viene.", pt_BR: "O Continuum está só começando. Veja o que vem a seguir.", de: "Continuum fängt gerade erst an. Das kommt als Nächstes.", fr: "Continuum ne fait que commencer. Voici la suite.", ja: "Continuum はまだ始まったばかりです。次に来るものをご紹介します。", zh_CN: "Continuum 才刚刚开始。接下来是这些。", ru: "Continuum только начинается. Вот что дальше.", ko: "Continuum은 이제 시작입니다. 다음은 이렇습니다.", it: "Continuum è appena agli inizi. Ecco cosa arriva.", tr: "Continuum daha yeni başlıyor. Sırada bunlar var." },
  Soon: { es: "Pronto", pt_BR: "Em breve", de: "Bald", fr: "Bientôt", ja: "近日", zh_CN: "即将推出", ru: "Скоро", ko: "곧", it: "Presto", tr: "Yakında" },
  "More models &amp; agents": { es: "Más modelos y agentes", pt_BR: "Mais modelos e agentes", de: "Mehr Modelle &amp; Agenten", fr: "Plus de modèles et d'agents", ja: "モデルとエージェントを拡大", zh_CN: "更多模型与智能体", ru: "Больше моделей и агентов", ko: "더 많은 모델과 에이전트", it: "Più modelli e agenti", tr: "Daha çok model ve ajan" },
  "Grok, DeepSeek, and Copilot join the resume picker, and a session can hand off to coding agents like Claude Code, alive from chat to editor and back.": { es: "Grok, DeepSeek y Copilot se suman al selector, y una sesión podrá pasar a agentes de código como Claude Code, viva del chat al editor y de vuelta.", pt_BR: "Grok, DeepSeek e Copilot entram no seletor, e uma sessão poderá passar para agentes de código como o Claude Code, viva do chat ao editor e de volta.", de: "Grok, DeepSeek und Copilot kommen in die Auswahl, und eine Sitzung kann an Coding-Agenten wie Claude Code übergeben — lebendig vom Chat zum Editor und zurück.", fr: "Grok, DeepSeek et Copilot rejoignent le sélecteur, et une session pourra passer à des agents de code comme Claude Code, vivante du chat à l'éditeur et retour.", ja: "Grok・DeepSeek・Copilot が再開先に加わり、セッションは Claude Code のようなコーディングエージェントへも引き継げるようになります。チャットからエディタへ、そしてまた戻って。", zh_CN: "Grok、DeepSeek 和 Copilot 将加入继续选择器，会话还能交接给 Claude Code 这类编码智能体，在对话与编辑器之间来回流转。", ru: "Grok, DeepSeek и Copilot появятся в выборе, а сессию можно будет передать кодинг-агентам вроде Claude Code — живой путь от чата к редактору и обратно.", ko: "Grok과 DeepSeek, Copilot이 이어하기 목록에 합류하고, 세션을 Claude Code 같은 코딩 에이전트로 넘길 수 있게 됩니다. 대화에서 에디터로, 다시 되돌아오도록.", it: "Grok, DeepSeek e Copilot entrano nel selettore, e una sessione potrà passare ad agenti di codice come Claude Code, viva dalla chat all'editor e ritorno.", tr: "Grok, DeepSeek ve Copilot sürdürme seçicisine katılıyor; bir oturum Claude Code gibi kodlama ajanlarına da devredilebilecek, sohbetten editöre ve geri." },
  "Sync to Obsidian &amp; Notion": { es: "Sincronizar con Obsidian y Notion", pt_BR: "Sincronizar com Obsidian e Notion", de: "Sync zu Obsidian &amp; Notion", fr: "Synchroniser vers Obsidian et Notion", ja: "Obsidian と Notion に同期", zh_CN: "同步到 Obsidian 与 Notion", ru: "Синхронизация с Obsidian и Notion", ko: "Obsidian과 Notion으로 동기화", it: "Sincronizza con Obsidian e Notion", tr: "Obsidian ve Notion'a senkronize et" },
  "Send every captured chat straight into your Obsidian vault or Notion workspace as a clean, linked note.": { es: "Envía cada chat capturado directamente a tu bóveda de Obsidian o a tu espacio de Notion como una nota limpia y enlazada.", pt_BR: "Envie cada conversa capturada direto para seu cofre do Obsidian ou workspace do Notion como uma nota limpa e vinculada.", de: "Schick jeden gesicherten Chat direkt als saubere, verlinkte Notiz in deinen Obsidian-Vault oder Notion-Workspace.", fr: "Envoyez chaque chat capturé directement dans votre coffre Obsidian ou votre espace Notion, sous forme de note propre et liée.", ja: "保存したチャットを、そのまま Obsidian の保管庫や Notion のワークスペースへ、整理されたリンク付きノートとして送ります。", zh_CN: "把每一段捕获的对话直接送进你的 Obsidian 库或 Notion 工作区，成为干净且带链接的笔记。", ru: "Отправляйте каждый сохранённый чат прямо в ваше хранилище Obsidian или рабочее пространство Notion — аккуратной заметкой со ссылками.", ko: "저장한 모든 대화를 Obsidian 보관함이나 Notion 워크스페이스로 바로 보내 깔끔하게 연결된 노트로 만듭니다.", it: "Invia ogni chat catturata direttamente nel tuo vault Obsidian o workspace Notion come nota pulita e collegata.", tr: "Yakaladığınız her sohbeti doğrudan Obsidian kasanıza ya da Notion çalışma alanınıza, düzenli ve bağlantılı bir not olarak gönderin." },
  "More export formats": { es: "Más formatos de exportación", pt_BR: "Mais formatos de exportação", de: "Mehr Exportformate", fr: "Plus de formats d'export", ja: "エクスポート形式を追加", zh_CN: "更多导出格式", ru: "Больше форматов экспорта", ko: "더 많은 내보내기 형식", it: "Altri formati di esportazione", tr: "Daha fazla dışa aktarma biçimi" },
  "Save a chat as HTML for a browsable, self-contained page, or as JSON for clean, structured data you can pipe anywhere.": { es: "Guarda un chat como HTML para tener una página navegable y autónoma, o como JSON para obtener datos estructurados que puedes llevar a cualquier parte.", pt_BR: "Salve uma conversa como HTML para ter uma página navegável e autossuficiente, ou como JSON para dados estruturados que você pode levar para qualquer lugar.", de: "Speichere einen Chat als HTML für eine in sich geschlossene, durchklickbare Seite — oder als JSON für saubere, strukturierte Daten, die du überall weiterverarbeiten kannst.", fr: "Enregistrez un chat en HTML pour une page autonome et navigable, ou en JSON pour des données structurées que vous pouvez envoyer n'importe où.", ja: "チャットを HTML として保存すれば単体で閲覧できるページに、JSON として保存すればどこにでも流し込める構造化データになります。", zh_CN: "把对话保存为 HTML，得到可浏览的独立页面；或保存为 JSON，得到可以接入任何流程的结构化数据。", ru: "Сохраните чат в HTML — получится самодостаточная страница для просмотра, или в JSON — чистые структурированные данные, которые можно передать куда угодно.", ko: "대화를 HTML로 저장하면 그대로 열어 볼 수 있는 독립 페이지가, JSON으로 저장하면 어디로든 넘길 수 있는 구조화된 데이터가 됩니다.", it: "Salva una chat come HTML per una pagina autonoma e navigabile, o come JSON per dati strutturati e puliti da inviare ovunque.", tr: "Bir sohbeti HTML olarak kaydedip gezilebilir, kendi kendine yeten bir sayfa elde edin; ya da JSON olarak kaydedip her yere aktarabileceğiniz düzenli, yapılandırılmış veri alın." },
  "A desktop app": { es: "Una app de escritorio", pt_BR: "Um app de desktop", de: "Eine Desktop-App", fr: "Une app de bureau", ja: "デスクトップアプリ", zh_CN: "桌面应用", ru: "Десктопное приложение", ko: "데스크톱 앱", it: "Un'app desktop", tr: "Bir masaüstü uygulaması" },
  "A native Continuum app to search, organize, and resume your entire chat library outside the browser.": { es: "Una app nativa de Continuum para buscar, organizar y continuar toda tu biblioteca de chats fuera del navegador.", pt_BR: "Um app nativo do Continuum para buscar, organizar e continuar toda a sua biblioteca de conversas fora do navegador.", de: "Eine native Continuum-App, um deine ganze Chat-Bibliothek außerhalb des Browsers zu durchsuchen, zu ordnen und fortzusetzen.", fr: "Une app Continuum native pour rechercher, organiser et reprendre toute votre bibliothèque de chats hors du navigateur.", ja: "ブラウザの外でチャットライブラリ全体を検索・整理・再開できる、Continuum のネイティブアプリ。", zh_CN: "一个原生的 Continuum 应用，让你在浏览器之外搜索、整理并继续整个对话库。", ru: "Нативное приложение Continuum, чтобы искать, упорядочивать и продолжать всю вашу библиотеку чатов вне браузера.", ko: "브라우저 밖에서 전체 대화 보관함을 검색하고 정리하고 이어갈 수 있는 네이티브 Continuum 앱.", it: "Un'app Continuum nativa per cercare, organizzare e riprendere l'intera libreria di chat fuori dal browser.", tr: "Tüm sohbet kitaplığınızı tarayıcı dışında aramanızı, düzenlemenizi ve sürdürmenizi sağlayan yerel bir Continuum uygulaması." },

  // ── Closing CTA + footer ──────────────────────────────────────────────
  "Bring your AI chats with you.": { es: "Llévate tus chats de IA contigo.", pt_BR: "Leve suas conversas de IA com você.", de: "Nimm deine KI-Chats mit.", fr: "Emportez vos chats IA avec vous.", ja: "AIとの会話を、持ち歩こう。", zh_CN: "把你的 AI 对话随身带走。", ru: "Заберите свои чаты с ИИ с собой.", ko: "AI 대화를 가지고 다니세요.", it: "Porta con te le tue chat IA.", tr: "Yapay zeka sohbetlerinizi yanınızda taşıyın." },
  "Install Continuum and stop losing context to length limits.": { es: "Instala Continuum y deja de perder contexto por los límites de longitud.", pt_BR: "Instale o Continuum e pare de perder contexto por causa dos limites de tamanho.", de: "Installiere Continuum und verlier keinen Kontext mehr an Längenlimits.", fr: "Installez Continuum et cessez de perdre du contexte à cause des limites de longueur.", ja: "Continuum を入れて、長さの上限で文脈を失うのをやめましょう。", zh_CN: "安装 Continuum，别再因为长度限制丢失上下文。", ru: "Установите Continuum и перестаньте терять контекст из-за лимитов длины.", ko: "Continuum을 설치하고 길이 제한 때문에 맥락을 잃는 일을 끝내세요.", it: "Installa Continuum e smetti di perdere contesto per i limiti di lunghezza.", tr: "Continuum'u kurun ve uzunluk sınırları yüzünden bağlam kaybetmeyi bırakın." },
  "Capture, save, and resume AI chats. Private by design.": { es: "Captura, guarda y continúa chats de IA. Privado por diseño.", pt_BR: "Capture, salve e continue conversas de IA. Privado por design.", de: "KI-Chats sichern, speichern und fortsetzen. Privat von Grund auf.", fr: "Capturez, sauvegardez et reprenez vos chats IA. Confidentiel par conception.", ja: "AIチャットを保存し、再開する。設計段階からプライベート。", zh_CN: "捕获、保存并继续 AI 对话。隐私优先。", ru: "Сохраняйте и продолжайте чаты с ИИ. Приватность по умолчанию.", ko: "AI 대화를 저장하고 이어가세요. 설계부터 프라이빗.", it: "Cattura, salva e riprendi le chat IA. Privato per progettazione.", tr: "Yapay zeka sohbetlerini yakalayın, kaydedin ve sürdürün. Tasarımdan gelen gizlilik." },
};

module.exports = { SITE2 };
